[package]
name = "belch_proxy_beta"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
ratatui = "0.20"
regex = "1.10"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1.37", features = ["full"] }
httparse = "1.8"
